/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Local_chatapp;

import static Local_chatapp.MulticastClient.name;
import static Local_chatapp.MulticastClient.s;
import java.net.*;
import java.io.*;
import java.util.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Morxidia
 */

public  class MulticastClient extends javax.swing.JFrame {
    public static String name;
    public static String message;
    public static MulticastSocket socket=null;
    public static InetAddress address ;  
    public static DatagramSocket s=null;
    /**
     * Creates new form MulticastServerThread
     */
    public MulticastClient(){
        initComponents();
        this.setLocationRelativeTo(null);
    }  
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sendBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        MessageWindow = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        messageBox = new javax.swing.JTextArea();
        msgBoxHeader = new javax.swing.JLabel();
        exitBtn = new javax.swing.JButton();
        Header = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        userList = new javax.swing.JTextArea();
        userListheader = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        sendBtn.setText("Send");
        sendBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendBtnActionPerformed(evt);
            }
        });

        MessageWindow.setEditable(false);
        MessageWindow.setColumns(20);
        MessageWindow.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        MessageWindow.setRows(5);
        MessageWindow.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jScrollPane1.setViewportView(MessageWindow);

        messageBox.setColumns(20);
        messageBox.setFont(new java.awt.Font("Gabriola", 1, 24)); // NOI18N
        messageBox.setRows(5);
        jScrollPane2.setViewportView(messageBox);

        msgBoxHeader.setFont(new java.awt.Font("Gabriola", 1, 24)); // NOI18N
        msgBoxHeader.setText("Message");

        exitBtn.setText("Exit from Chat");
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });

        Header.setFont(new java.awt.Font("Gabriola", 1, 24)); // NOI18N
        Header.setText("Chat Window");

        userList.setEditable(false);
        userList.setColumns(20);
        userList.setRows(5);
        jScrollPane3.setViewportView(userList);

        userListheader.setFont(new java.awt.Font("Gabriola", 1, 24)); // NOI18N
        userListheader.setText("Online users");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Header, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 500, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 573, Short.MAX_VALUE)
                            .addComponent(jScrollPane1)
                            .addComponent(msgBoxHeader, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(userListheader)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(sendBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(exitBtn))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userListheader)
                    .addComponent(Header))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)
                        .addGap(3, 3, 3)
                        .addComponent(exitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sendBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(msgBoxHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        String x= name + " has logged out from the chat room *****";
            byte buf[]=x.getBytes();
              try{
                InetAddress group = InetAddress.getByName("230.0.0.1");
                DatagramPacket packet = new DatagramPacket(buf, buf.length, group, 4446);
                s.send(packet);
              }
              catch(Exception e){
                  System.err.println(e);
              }
              
        x="exited";
        buf=x.getBytes();
        
        try{
            InetAddress group=InetAddress.getByName("230.0.0.2");
            DatagramPacket packet=new DatagramPacket(buf, buf.length,group,5000);
            s.send(packet);
            socket.leaveGroup(address);
            s.close();
        }
        catch(Exception e){
            System.err.println(e);
        }
        this.setVisible(false);
        new ChatApp().setVisible(true);   
    }//GEN-LAST:event_exitBtnActionPerformed

    private void sendBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendBtnActionPerformed
        String text= messageBox.getText();
         if(!text.equals(""))
         {    message=name+": "+text;
         try {
             
                byte[] buf ;
 
                  
                                 
                   
                buf = message.getBytes();
             
            // send it
          
                InetAddress group = InetAddress.getByName("230.0.0.1");
                DatagramPacket packet = new DatagramPacket(buf, buf.length, group, 4446);
               
              s.send(packet);  
            
           
               }       
         catch (IOException e) {
               // System.out.println(e);
                 MulticastClient.socket.close();
         }   }
    }//GEN-LAST:event_sendBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
       
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                
                    new MulticastClient().setVisible(true);
                
                    }
               }
        );
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Header;
    public static javax.swing.JTextArea MessageWindow;
    private javax.swing.JButton exitBtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    public static javax.swing.JTextArea messageBox;
    private javax.swing.JLabel msgBoxHeader;
    private javax.swing.JButton sendBtn;
    public static javax.swing.JTextArea userList;
    private javax.swing.JLabel userListheader;
    // End of variables declaration//GEN-END:variables
}

class Client implements Runnable {
    Client(){
         try{
            MulticastClient.socket = new MulticastSocket(4446) ;
            MulticastClient.s=new DatagramSocket();
            MulticastClient.address=InetAddress.getByName("230.0.0.1");
            MulticastClient.socket.joinGroup(MulticastClient.address);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(new ChatApp(), "Sorry,Cannot bind");
        }
     }
 
    @Override
    public void run(){
        Thread t3=new Thread(new OnlineStatus());
        t3.start();
        Thread t4=new Thread(new ReceiveOnlineStatus());    
        t4.start();
        newUser();
        while(true){  
            try{
                DatagramPacket packet;
                byte[] buf = new byte[256];
                packet = new DatagramPacket(buf, buf.length);
                MulticastClient.socket.receive(packet);
                String received = new String(packet.getData(), 0, packet.getLength());
                MulticastClient.MessageWindow.setText(MulticastClient.MessageWindow.getText()+received+"\n");
                MulticastClient.messageBox.setText("");
            }
            catch(IOException e){
                System.err.println(e);
            }
        }
    } 
    
    void newUser(){
        String x= name+" has logged into the chat room";
        byte buf[]=x.getBytes();
        try{  
            InetAddress group = InetAddress.getByName("230.0.0.1");
            DatagramPacket packet = new DatagramPacket(buf, buf.length, group, 4446);
            s.send(packet);
        }
        catch(Exception e){
            System.err.println(e);
        }
    }
}